### PR TITLE
Various fixes to Unix build system

### PR DESCRIPTION
**Pull request by svillemot**
The Unix build is essentially unusable. This patch makes it functional. It is applied to the Debian package.

### CODE REVIEW

**Comment by KybernetikJo** [comment]
@svillemot 

When I run your PR with the command

make -f makefile_Unix lib FFLAGS="" BLASLIB="-L/usr/lib/x86_64-linux-gnu/blas -lblas" LAPACKLIB="-L/usr/lib/x86_64-linux-gnu/lapack -llapack"

I get a file "slicot.a".

If I run it without `lib`

make -f makefile_Unix FFLAGS="" BLASLIB="-L/usr/lib/x86_64-linux-gnu/blas -lblas" LAPACKLIB="-L/usr/lib/x86_64-linux-gnu/lapack -llapack"

the compilation gets stuck at

./TAB01ND <AB01ND.dat >AB01ND.exa

Do you have any advice on how to fully compile your PR on Ubuntu 22.04? What is my error?
Mabye for FFLAGS=?

**Comment by svillemot** [comment]
I am only interested in building the library, so I only tested the `lib` target. It is possible that further fixes are needed when building the default target.

**Comment by VasileSima4** [comment]
Thank you for pointing out the errors in the Unix-like makefiles.  I have had limited
possibilities to check these files, and I have now no access to Unix-like machines.
Unfortunately, your request to merge your commit into SLICOT cannot be accepted, 
since other changes are still needed.  In my understanding, the link process is 
still not working at this time.  Also, you have deleted some file names in 
src/makefile_Unix, which appear in the new version 5.9, but also zelgtg, 
which is referred to by some routines.

Therefore, I made changes in the makefiles to include your useful suggestions.
But I also wanted to minimize the number of these changes.  For instance, by 
replacing FC by FORTRAN and FFLAGS by OPTS in make_Unix.inc, no changes are 
needed in the makefiles from the examples and src_aux subdirectories.  
The essential changes I made were:
- make_Unix.inc: changed ARFLAGS to ARCHFLAGS, FFLAGS by OPTS and added a line for "LOADER";
- makefile_Unix: added six references to make_Unix.inc;
- src/makefile_Unix: added a reference to make_Unix.inc.
In addition, I used the Unix convention for the end of lines.

I replaced these makefiles on GitHub.
 
Could you please try these new versions to also link the example programs 
(i.e., with the default make option) and let me know the results?
Thanks in advance.

**Comment by svillemot** [comment]
Thanks, the changes in a037f7eb76134d45e7d222b7f017d5cbd16eb731 look good to me. Closing.

**Pull request closed without merging**
